### ISSUE TITLE
Environment and config mismatch

### ISSUE THREAD

**Issue by gengen1988** [openfrontier/docker-gerrit#103]
https://github.com/openfrontier/docker-gerrit/blob/9fa31ce28ed7583281d3a1d331c987a3aedc09a7/gerrit-entrypoint.sh#L109

`NOTEDB_ACCOUNTS_SEQUENCEBATCHSIZE` should be `NOTEDB_CHANGES_AUTOMIGRATE`

**Comment by thinkernel** [comment]
Yes. Thank you.
I'll fix it.
