### ISSUE TITLE
External PostgreSQL SSL required

### ISSUE THREAD

**Issue by Novitoll** [openfrontier/docker-gerrit#104]
Need to add the SSL=true condition, perhaps in JDBC

https://gerrit-review.googlesource.com/Documentation/config-gerrit.html#database.url

**Comment by Novitoll** [comment]
```
Upgrading gerrit...
fatal: DbInjector failed
fatal: Unable to determine SqlDialect
fatal:   caused by org.postgresql.util.PSQLException: FATAL: SSL connection is required. Please specify SSL options and retry.
```

**Comment by thinkernel** [comment]
The database.url option is supported. Let me know if it can solve your issue, please.

**Comment by ohmerhe** [comment]
Why not just support SSL config for database?

**Comment by thinkernel** [comment]
@ohmerhe 
If you can let me know your preferred setup on SSL database config, I can figure out  how to support it.
