### ISSUE TITLE
[ Question ] Stuck on "Waiting for DB connection..."

### ISSUE THREAD

**Issue by ShonInDim** [openfrontier/docker-gerrit#109]
I trying to start docker-gerrit container with external PostgresDB (running on localhost) and it's only hanging on DB connection nothing more happened.

Doing like :

1. clone repo; build image from Dockerfile.
2.  run container from image 
 *  docker run --name gerrit \
 * -p 8081:8081 \
 * -p 29418:29418 \
 * -e WEBURL=http://173.***.***.***:8081 \
 * -e DATABASE_TYPE=postgresql \
 * -e DB_PORT_5432_TCP_ADDR=127.0.0.1 \
 * -e DB_PORT_5432_TCP_PORT=5432 \
 * -e DB_ENV_POSTGRES_DB=reviewdb \
 * -e DB_ENV_POSTGRES_USERE=gerrit2 \
 * -e DB_ENV_POSTGRES_PASSWORD=gerrit \
 * -d gerritpenfro \`

3. `docker logs -f gerrit`
`Generating SSH host key ... rsa... dsa... ed25519... ecdsa 256... ecdsa 384... ecdsa 521... done
 Initialized /var/gerrit/review_site
 /gerrit-entrypoint.sh: ignoring /docker-entrypoint-init.d/*
 Waiting for database connection 127.0.0.1:5432...` 

4. while DB running on 
* tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      9507/postgres
* tcp6       0      0 ::1:5432                :::*                    LISTEN      9507/postgres
* udp6   16896      0 ::1:44157               ::1:44157               ESTABLISHED 9507/postgres

& has a valid user gerrit2 with password respectively. 

Could you give me advice what exactly should I do to run gerrit within container and external existing Postgres DB ?
May be I doing something wrong ?
Thank you in advance.

**Comment by ShonInDim** [comment]
> Would you please try `DATABASE_DATABASE, DATABASE_HOSTNAME, DATABASE_PASSWORD, DATABASE_USERNAME` then tell me tell what happens?

Sure, I can try it later today.
But I thought `DATABASE_DATABASE, DATABASE_HOSTNAME, DATABASE_PASSWORD, DATABASE_USERNAME` used in case of DB as separate container, isn't it ?

**Comment by ShonInDim** [comment]
`DATABASE_DATABASE ` is it name of my local DB, right ?
and should I sign `DATABASE_HOSTNAME` as `IP_ADDR:PORT [127.0.0.1:5432]` ?
So I tried :
docker run --name gerrit 
 * -p 8081:8081 
 * -p 29418:29418  
 * -e WEBURL=http:173.***.***.***:8081 
 * -e DATABASE_TYPE=postgresql 
 * -e DATABASE_DATABASE=reviewdb 
 * -e DATABASE_HOSTNAME=127.0.0.1:5432 
 * -e DATABASE_USERNAME=gerrit2 
 * -e DATABASE_PASSWORD=gerrit
it's returned :

> First time initialize gerrit...
ls: /var/gerrit/review_site/git: No such file or directory
[2018-11-06 17:30:23,257] [main] INFO  com.google.gerrit.server.config.GerritServerConfigProvider : No /var/gerrit/review_site/etc/gerrit.config; assuming defaults
Generating SSH host key ... rsa... dsa... ed25519... ecdsa 256... ecdsa 384... ecdsa 521... done
Initialized /var/gerrit/review_site

>/gerrit-entrypoint.sh: ignoring /docker-entrypoint-init.d/*

>Upgrading gerrit...
fatal: DbInjector failed
fatal: Unable to determine SqlDialect
fatal:   caused by org.postgresql.util.PSQLException: The connection attempt failed.
fatal:   caused by java.net.UnknownHostException: [127.0.0.1:5432]

I guess now problem is [127.0.0.1:5432] 
how may I assign DB host name to connecting properly ?

**Comment by ShonInDim** [comment]
as I thought this issue linked with docker networking;
if add `--net=host` key:value param docker-gerrit container successfully connected to local Postgres db.
Now I have another problem with db schema, but it's another separate  case, so I do it on my own.

**Comment by thinkernel** [comment]
Glad to hear that you have solved this issue.
Those DB_* environment variables are designed to work with docker --link which is kind of legacy. That's why DATABASE_* environment variables are introduced. These environment variables can be used with any kind of external databases, containerized or not.
