### ISSUE TITLE
[Question] Errors/warnings logging into file.

### ISSUE THREAD

**Issue by ShonInDim** [openfrontier/docker-gerrit#111]
Hello!

  For now it's only `delete_log, gc_log, httpd_log, import_log, sshd_log, replication_log` writing info files,
but errors/warnings (if it occurred) returns to console log.
Is is possible to write errors/warnings logs to regular error_log file when docker container starts successfully ? 
or it is writes into error_log only if container start failed ?
```
gerrit-entrypoint.sh
.....
echo "Something wrong..."
    cat "${GERRIT_SITE}/logs/error_log"
```

As I understood from docs it could be this way in case of 
`java -jar gerrit.wat daemon --console-log`
```--console-log
Send log messages to the console, instead of to the standard log file $site_path/logs/error_log.
```
Meanwhile `gerrit-entrypoint.sh` doesn't run such a command.

**Comment by thinkernel** [comment]
I wonder if [this ](https://github.com/openfrontier/docker-gerrit#override-the-default-startup-action)can answer your request?

**Comment by ShonInDim** [comment]
Yep, I did not notice that passage.
Excuse my carelessness.
