### ISSUE TITLE
Wrong hostname after login/logout

### ISSUE THREAD

**Issue by mmuejde** [openfrontier/docker-gerrit#115]
After login or logout the redirect is wrong. Its like <container-id>/logout...

ENV's

WEBURL = https://gerrit.vencortex.com

<img width="606" alt="Screenshot 2019-05-09 at 14 47 48" src="https://user-images.githubusercontent.com/24757679/57454640-99dc6080-7269-11e9-9b78-1f69ec0b5c24.png">

**Comment by thinkernel** [comment]
Besides WEBURL，HTTPD_LISTENURL should be set like "proxy-http://*:8080/gerrit" if your Gerrit is behind a proxy.

**Comment by mmuejde** [comment]
I have already find the problem. I habe used https instead of http in the env WEBURL.
