### ISSUE TITLE
Configuration of remotes for replication

### ISSUE THREAD

**Issue by hubertba** [openfrontier/docker-gerrit#116]
Hi

I try to figure out how to configure remotes for replication.
Can someone post a sample set of parameters which generate a valid config ?

**Comment by hubertba** [comment]
got my problem .. remoteNames with a dash ( - ) in it are not working.

**Comment by thinkernel** [comment]
Hi @hubertba 
Thanks for the information. Could you please tell me what kind of remote you are using?
