### ISSUE TITLE
Error: "cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory"

### ISSUE THREAD

**Issue by mmuejde** [openfrontier/docker-gerrit#117]
gerrit             | Reindexed 2 documents in projects index in 0.1s (14.7/s)
gerrit             | cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory
gerrit             | cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory
gerrit             | cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory
gerrit             | cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory
gerrit             | cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory
gerrit             | cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory
gerrit             | cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory
gerrit             | cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory
gerrit             | cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory
gerrit             | cp: can't stat '/var/gerrit/delete-project.jar': No such file or directory

**Comment by thinkernel** [comment]
Thanks for the issue report. 
Let me know if the latest commit fixed your issue.

**Comment by mmuejde** [comment]
Bug fixed. Thanks:)
