### ISSUE TITLE
how can gerrit container be destination server of plugin replication

### ISSUE THREAD

**Issue by kunlinyu** [openfrontier/docker-gerrit#125]
I deployed one gerrit server without any docker technologies and I want to deploy a new gerrit server as a backup using docker run. And I want to push every thing from the old server(without docker) to new server(with docker).
I followed replication's document but I got confused by one question:
If I want to replicate from source server to destination server, the source server must have permission to access the destination server through ssh protocol. But which port and user? Is it the gerrit user through port 29418 OR linux user through port 22?
I guess it is the gerrit user and port 29418. But I failed. According to the log of replication, it can not push anything and get an error "Auth fail".
So I think the user linux user and port is 22. Then I try to ssh login into gerrit container but I got "connection confused". So I think there is no ssh server running on 22 port in this image.

I'm I correct and what should I do?

**Comment by thinkernel** [comment]
I think the ssh port should be 29418. It's like a git push over ssh.
BTW, you can't bind your container's ssh port to host's 22 port because it's occupied by sshd service in your host.

**Comment by kunlinyu** [comment]
Thank you. I get that the user is gerrit user not linux user and the port should be 29418.
