### ISSUE TITLE
Oauth plugin in 3.1.3 at Dockerhub has critical bug 

### ISSUE THREAD

**Issue by NikolayMarusenko** [openfrontier/docker-gerrit#126]
Could your, please, rebuild image 3.1.3 in Dockerhub, because current image has the following bug : (https://github.com/davido/gerrit-oauth-provider/issues/139) in Oauth plugin.

**Comment by thinkernel** [comment]
Hi @NikolayMarusenko 
I rebuilt the openfrontier/gerrit:latest image by upgrading master branch to 3.1.4. 
Would you please give it a try and let me know if this issue is fixed.

**Comment by NikolayMarusenko** [comment]
Hi @thinkernel 
Issues fixed in openfrontier/gerrit:latest image . Would you please specify image tag?

**Comment by thinkernel** [comment]
No problem. The 3.1.4 has been released. Thanks for reporting the issue.
