### ISSUE TITLE
Add HTTP/HTTP_LDAP Auth Support 

### ISSUE THREAD

**Issue by michelvocks** [openfrontier/docker-gerrit#24]
Would love to see support for HTTP/HTTP__LDAP Auth in docker-entrypoint.sh.

**Comment by thinkernel** [comment]
Please checkout the latest image and tell me if that's what you need.

**Comment by michelvocks** [comment]
@thinkernel Perfect. Thank you very much! :+1:

**Comment by michelvocks** [comment]
Stupid me. Can you also add a variable for "auth.httpHeader"? It is by default not "X-Forwarded-User" which is the normal header key when you use a Reverse Proxy.

**Comment by thinkernel** [comment]
Pull the latest images, please.
I also added support for auth.emailFormat and auth.gitBasicAuth besides auth.httpHeader in case you might need them.

**Comment by michelvocks** [comment]
Great. Works fine. Thank you.
