### ISSUE TITLE
LDAP_SERVER is hardcoded to ldap

### ISSUE THREAD

**Issue by renflo** [openfrontier/docker-gerrit#27]
Hi,
`gerrit-entrypoint.sh` contains the following line:

```
[ -z "${LDAP_SERVER}" ]                   || set_gerrit_config ldap.server "ldap://${LDAP_SERVER}"
```

Configuring a ldaps is non trivial as the `ldap` scheme is hardcoded. Could the script set ldap.server exactly as passed in the environment variable? 

```
[ -z "${LDAP_SERVER}" ]                   || set_gerrit_config ldap.server "${LDAP_SERVER}"
```

If not possible could you add support for some way to provide the scheme?

**Comment by thinkernel** [comment]
It's a good idea.
But, it's a big change that will make lots of existed users have to change their configuration when they pull the latest image. So I have to figure out a way to let them know the change.

**Comment by renflo** [comment]
what about (haven´t tested it, it´s for the sake of discussion)
```
[ -z "${LDAP_SERVER}" ]                   ||  [ -z "${LDAP_SCHEME}" ]  &&set_gerrit_config ldap.server "ldap://${LDAP_SERVER}"          || set_gerrit_config ldap.server "${LDAP_SCHEME}://${LDAP_SERVER}"
```

Should not break anything for anyone.

**Comment by thinkernel** [comment]
That's a good idea for backward compatibility. But it introduces a new variable which isn't existed in the gerrit.config file. And I have to write it into the README in order to explain how to use it which make me think it might be as same as just change the usage of the LDAP_SERVER which also have to be documented into the README file.

**Comment by renflo** [comment]
I guess if your goal is to mirror the configuration in gerrit.config as closely as possible then yes, ${LDAP_SERVER} should include the scheme (and introducing a breaking change might be justified).

**Comment by thinkernel** [comment]
Fixed.
Checkout the latest image and let me know if it works, please.

**Comment by thinkernel** [comment]
@renflo 
Would you please let me know if this issue can be closed?

**Comment by renflo** [comment]
@thinkernel sorry for the delay. I will retest now and let you know.
