### ISSUE TITLE
AUTH_TYPE=HTTP  configuration

### ISSUE THREAD

**Issue by bkbonner** [openfrontier/docker-gerrit#29]
I'm trying to setup GERRIT using the Docker image and it's giving me a configuration error.   

I'm using:

docker run --name gerrit --volumes-from gerrit_volume -p 8084:8080 -p 29418:29418 -e WEBURL=http://10.23.10.214:8084 -e SMTP_SERVER=smtp.na.jnj.com -e SMTP_SERVER_PORT=25 -e SMTP_ENCRYPTION=tls -e SMTP_CONNECT_TIMEOUT=10sec -e SMTP_FROM=USER -e AUTH_TYPE=HTTP -d openfrontier/gerrit

The error is:

The HTTP server did not provide the username in the Authorization header when it forwarded the request to Gerrit Code Review.

If the HTTP server is Apache HTTPd, check the proxy configuration includes an authorization directive with the proper location, ensuring it ends with '/':

<VirtualHost localhost:8084>
    ServerName localhost

```
ProxyRequests Off
ProxyVia Off
ProxyPreserveHost On

<Proxy *>
      Order deny,allow
      Allow from all
</Proxy>

<Location /login/>
  AuthType Basic
  AuthName "Gerrit Code Review"
  Require valid-user
  ...
</Location>

AllowEncodedSlashes On
ProxyPass / http://.../ nodecode
```

</VirtualHost>

I don't see anything about configuration of HTTP beyond the -e AUTH_TYPE = HTTP. 

Is there something I'm missing?

**Comment by thinkernel** [comment]
Try adding this one to your command line.
 -e HTTPD_LISTENURL=proxy-http://*:8080 \

**Comment by bkbonner** [comment]
Does this configuration require that I have an http server setup in front
of gerrit as an external configuration?   Or is it included as part of the
install?

Brian

**Comment by thinkernel** [comment]
Yes. That means you need to setup a http server as a reverse proxy. Auth_TYPE=HTTP means you want to provide the authentication in your proxy. Gerrit doesn't provide any authentication method itself. You have to choose between OpenID, Oauth, LDAP and HTTP providers.
