### ISSUE TITLE
gitweb not shown in the Projects/list

### ISSUE THREAD

**Issue by thincal** [openfrontier/docker-gerrit#36]
Bellow config is already in the gerrit.config file:
```
[gitweb]
	cgi = /usr/share/gitweb/gitweb.cgi
	url = /usr/share/gitweb
```

But I still can't find out the gitweb link from the Projects/list.

**Comment by thincal** [comment]
After switch to gerrit v2.12, the gitweb is shown normally.

**Comment by thinkernel** [comment]
Yes, I notice the issue, too. The gitweb setting seems not working in 2.13.x. Still trying to figure out where's the problem....

**Comment by joan38** [comment]
Hi,

Do you have any news on that?
I can't find why it doesn't work.

https://gerrit-review.googlesource.com/Documentation/config-gitweb.html

Cheers

**Comment by thinkernel** [comment]
I figure it out!

gitweb.type=gitweb  <- This become necessary since 2.13.

> If not set, or set to disabled, there is no gitweb hyperlinking support.

I will fix it.

**Comment by joan38** [comment]
@thinkernel Nice
Do you know if this setting is to be able to use gitiles or other?

**Comment by joan38** [comment]
I opened a PR

**Comment by joan38** [comment]
@thinkernel When are you pushing the new docker image that contains this change?

**Comment by thinkernel** [comment]
@joan38 
It's an automated build image so I think this should have been contained in the latest image. 
Anything wrong?

**Comment by joan38** [comment]
Great, I didn't try actually.
Thanks @thinkernel
