### ISSUE TITLE
Specifying LDAP_ACCOUNTSCOPE results in a crash

### ISSUE THREAD

**Issue by dmclain** [openfrontier/docker-gerrit#4]
When specifying LDAP_ACCOUNTSCOPE, a docker run fails with 
```
First time initialize gerrit...
Generating SSH host key ... rsa(simple)... done
Initialized /var/gerrit/review_site
error: unknown switch `c'
```

The problem appears to be at https://github.com/openfrontier/docker-gerrit/blob/master/gerrit-entrypoint.sh#L40 where `git config -cd` is used instead of `git config -f`

**Comment by thinkernel** [comment]
@dmclain 
I fixed LDAP_ACCOUNTSCOPE days ago. Does it work for you?
I just want to know if this issue can be closed.
