### ISSUE TITLE
How to start without initialization?

### ISSUE THREAD

**Issue by crorvick** [openfrontier/docker-gerrit#45]
The ENTRYPOINT script does a bunch of initialization if run with the default CMD `/gerrit-start.sh`, including re-indexing.  This can take a long time so ideally this would only be done on initial setup.  It's not clear how to bypass this, though.

**Comment by crorvick** [comment]
Generating the index offline seems to be unnecessary since Gerrit 2.11.2.  I've submitted a [pull request](https://github.com/openfrontier/docker-gerrit/pull/46) with a potential solution.

**Comment by crorvick** [comment]
Pull request #46 resolves the issue of extended startup times and has been merged.  Thanks!

**Comment by thinkernel** [comment]
You're welcome and thanks for the patch.
