### ISSUE TITLE
latest image on dockerhub is missing the version specific tag of 2.13.5

### ISSUE THREAD

**Issue by electrofelix** [openfrontier/docker-gerrit#49]
Minor nit, like pinning to the specific version instead of using the 'latest' tag (except when experimenting), however it seems the latest build which is 2.13.5 based appears to be missing a tag identifying it separately to latest.

Would it be possible to have it tagged?

Thanks in advance.

**Comment by thinkernel** [comment]
I just created a 2.13.5 tag based on master branch. You're right. I should separate latest tag to the latest release tag like 2.13.5. In this way, the latest image can be used to introduce some new features.

**Comment by electrofelix** [comment]
Thanks! and confirmed available as well.
