### ISSUE TITLE
What is with Bitbucket OAuth support?

### ISSUE THREAD

**Issue by symonsoft** [openfrontier/docker-gerrit#63]
Please, consider adding **OAUTH_BITBUCKET_CLIENT_ID**, **OAUTH_BITBUCKET_CLIENT_SECRET** and **OAUTH_BITBUCKET_FIX_LEGACY_USER_ID** variables.

**Comment by thinkernel** [comment]
I think I can do something for this. I'm working on the 2.14 release recently. I'll check this one after the v2.14 image.

**Comment by thinkernel** [comment]
@symonsoft 
The support for Bitbucket OAuth has been added.
Please download the latest image and let me know if it works for you.

**Comment by thinkernel** [comment]
I tested it myself. It seems that it works on 2.13.x. However, there're some problems on 2.14.
It relates to [this issue](https://gerrit-review.googlesource.com/c/98997/) and [this one](https://gerrit-review.googlesource.com/c/96370/37/gerrit-httpd%252Fsrc%252Fmain%252Fjava%252Fcom%252Fgoogle%252Fgerrit%252Fhttpd%252FGitOverHttpModule.java#46).

**Comment by thinkernel** [comment]
Issues on master branch are fixed though git over http is not supported on oauth right now.
