### ISSUE TITLE
link environment variables are superseded

### ISSUE THREAD

**Issue by terinjokes** [openfrontier/docker-gerrit#64]
In our environment, which uses version 2 of the docker composer format, docker no longer sets the superseded [link environment variables][1]. Unfortunately, if using a database other than H2, this project assumes the link environment variables are set.

[1]: https://docs.docker.com/compose/link-env-deprecated/

While I can set the link environment variables in the docker-compose file, it would be great if they had more descriptive names than `DB_PORT_5432_TCP_ADDR` 😉

**Comment by thinkernel** [comment]
[This project](https://github.com/openfrontier/ci-compose) might be an example for your question.

**Comment by terinjokes** [comment]
@thinkernel: yep, that's exactly what I did internally.

Again, not difficult once you take a peak at the entrypoint, but also not something that's magic anymore.

**Comment by thinkernel** [comment]
In the case of using compose, that's true. But `--link` still works with `docker run` command. So it may not be the best time for us to change the name of that environment variable.

**Comment by thinkernel** [comment]
External database options are supported in #93. So I think this can be closed.
