### ISSUE TITLE
 "docker run -d -p 8080:8080 -p 29418:29418 -e AUTH_TYPE=HTTP openfrontier/gerrit" doesn't work

### ISSUE THREAD

**Issue by jimmy-peng** [openfrontier/docker-gerrit#68]
When I exec this command and access the web interface 8080, it does't work.

**Comment by thinkernel** [comment]
https://gerrit-review.googlesource.com/Documentation/config-gerrit.html#auth

> HTTP
> 
> Gerrit relies upon data presented in the HTTP request. This includes HTTP basic authentication, or some types of commercial single-sign-on solutions. With this setting enabled the authentication must take place in the web server or servlet container, and not from within Gerrit.
> 

You need a web server in front of the Gerrit to do the authentication.

**Comment by jimmy-peng** [comment]
Thank you a lot
