### ISSUE TITLE
How can I use NoteDB with this docker image?

### ISSUE THREAD

**Issue by mistyharsh** [openfrontier/docker-gerrit#77]
I am not expert in Gerrit Setup, but what I understand is Gerrit now supports [NoteDB](https://gerrit.googlesource.com/homepage/+/md-pages/docs/Notedb.md). This option gets rid of SQL database dependency which is very desirable for us.

I was going through docs, but did not find any options to use this. Any way how I can utilize this option. This [link](https://gerrit-review.googlesource.com/Documentation/note-db.html) explains it in details.

**Comment by thinkernel** [comment]
Hi @mistyharsh 
Thank you for letting me know the NoteDB option which is introduced in 2.15 RC. A branch has been created for the 2.15 RC. Also, openfrontier/gerrit:2.15.rc is also available. This branch and image will be existed until 2.15 is released. I think features about notedb should be submitted in that branch currently.

**Comment by thinkernel** [comment]
The 2.15.x branch is created. You can use releases on this branch for notedb feature now. I think this issue can be clolsed.
