### ISSUE TITLE
If DB is Postgres and if you restart container, All-projects missing error occurrs

### ISSUE THREAD

**Issue by Novitoll** [openfrontier/docker-gerrit#88]
Need to check if All-Projects presents in Postgres. In H2 DB this is done during build time.

https://bugs.chromium.org/p/gerrit/issues/detail?id=1305

**Comment by thinkernel** [comment]
I can't believe it happens again. I'v done [this](https://github.com/openfrontier/docker-gerrit/blob/master/gerrit-entrypoint.sh#L38) on purpose to avoid this problem. Did you occur this problem in a fresh new installation or an upgrade process?

**Comment by Novitoll** [comment]
Not sure what happened. That bash script should do the thing. Closing this as it's not reproducable with PosgreSQL
