### ISSUE TITLE
[Query] Will there be a 2.14.x branch added to track 2.14 releases?

### ISSUE THREAD

**Issue by electrofelix** [openfrontier/docker-gerrit#92]
Noticed there are `2.13.x 2.12.x` branches with corresponding images in dockerhub, will there be a `2.14.x` branch created as well?

Currently it looks like it's not possible to get the `2.14.8` release except by pointing at the `latest`, however I'm assuming that will go to 2.15.x in the near future?

**Comment by thinkernel** [comment]
I'm working on switching master branch to track 2.15.x. The 2.14.x branch will be created when master has been changed to 2.15.x. I forgot to create the 2.14.8 branch. It will be created ASAP.

**Comment by thinkernel** [comment]
The 2.14.x branch and also a 2.15.x branch is there already. This issue can be closed.

**Comment by electrofelix** [comment]
@thinkernel thanks, much appreciated
